### ISSUE TITLE
add note about luma.lcd in readme

### ISSUE THREAD

**Issue by thijstriemstra** [rm-hull/st7735fb#4]
This project is deprecated isn't it?

**Comment by rm-hull** [comment]
Yes its deprecated inasmuch as the framebuffer drivers are now build as kernel objects inside RPi linux.

Although this project and luma.lcd both make use of st7735 displays, they do it in completely different ways and luma.lcd doesn't really replace this project.

**Comment by thijstriemstra** [comment]
Alright cool.
